# Generated by Django 5.0.3 on 2024-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionApp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiondetails',
            name='auctio_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctiondetails',
            name='auctio_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
