# Generated by Django 5.0.3 on 2024-03-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionApp', '0004_alter_auctiondetails_auctio_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiondetails',
            name='auctio_end_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auctiondetails',
            name='auctio_start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
